AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'config/spring.rb'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Style/AsciiComments:
  Enabled: false